clc

Ts = 125e-6; % PERIODA VZORKOVANI!!!
A = 5;       % AMPLITUDA VSTUPNIHO SINUSOVEHO SIGNALU!!!
f = 400;       % FREKVENCE VSTUPNI SINUSOVEHO SIGNALU!!!
offset = 6;     % CEKANI NEZ SE SPUSTI IDENTIFIKACE!!!